import type { TriviaQuestion } from '@repo/games';

/**
 * Initial trivia bank (draft for review: docs/contenido/preguntas.md).
 * options[0] is always the correct answer; players see the options shuffled.
 * Difficulty: 1 easy, 2 medium, 3 hard. Every day uses two easy, two medium and one hard.
 */
export const TRIVIA_QUESTIONS: readonly TriviaQuestion[] = [
  // Argentina
  { id: 'ar-flor-nacional', category: 'argentina', difficulty: 1, prompt: '¿Cuál es la flor nacional de la Argentina?', options: ['El ceibo', 'El jacarandá', 'La rosa', 'El girasol'] },
  { id: 'ar-ave-nacional', category: 'argentina', difficulty: 2, prompt: '¿Qué ave es considerada el ave nacional de la Argentina?', options: ['El hornero', 'El cóndor', 'El ñandú', 'El tero'] },
  { id: 'ar-9-de-julio', category: 'argentina', difficulty: 1, prompt: '¿Qué día se celebra la Independencia argentina?', options: ['El 9 de julio', 'El 25 de mayo', 'El 20 de junio', 'El 17 de agosto'] },
  { id: 'ar-25-de-mayo', category: 'argentina', difficulty: 1, prompt: '¿Qué se conmemora el 25 de mayo?', options: ['La Revolución de Mayo', 'La Independencia', 'El Día de la Bandera', 'El Día del Trabajador'] },
  { id: 'ar-bandera-creador', category: 'argentina', difficulty: 1, prompt: '¿Quién creó la bandera argentina?', options: ['Manuel Belgrano', 'José de San Martín', 'Domingo F. Sarmiento', 'Mariano Moreno'] },
  { id: 'ar-bandera-colores', category: 'argentina', difficulty: 1, prompt: '¿Cuáles son los colores de la bandera argentina?', options: ['Celeste y blanco', 'Azul y blanco', 'Celeste y amarillo', 'Blanco y rojo'] },
  { id: 'ar-provincias', category: 'argentina', difficulty: 2, prompt: '¿Cuántas provincias tiene la Argentina?', options: ['23', '24', '22', '25'] },
  { id: 'ar-capital-bsas', category: 'argentina', difficulty: 2, prompt: '¿Cuál es la capital de la provincia de Buenos Aires?', options: ['La Plata', 'Mar del Plata', 'Bahía Blanca', 'Ciudad de Buenos Aires'] },
  { id: 'ar-mate', category: 'argentina', difficulty: 1, prompt: '¿Con qué se toma el mate?', options: ['Con bombilla', 'Con cuchara', 'Con sorbete', 'Con tenedor'] },
  { id: 'ar-mate-ronda', category: 'argentina', difficulty: 1, prompt: '¿Qué infusión típica se comparte en ronda?', options: ['El mate', 'El té', 'El café', 'El chocolate'] },
  { id: 'ar-alfajor', category: 'argentina', difficulty: 1, prompt: '¿Qué golosina tiene dos tapitas y relleno, muchas veces de dulce de leche?', options: ['El alfajor', 'La medialuna', 'La pastafrola', 'La garrapiñada'] },
  { id: 'ar-asado', category: 'argentina', difficulty: 1, prompt: '¿Qué comida típica argentina se hace a la parrilla?', options: ['El asado', 'El locro', 'La paella', 'El sushi'] },
  { id: 'ar-locro', category: 'argentina', difficulty: 2, prompt: '¿Qué plato típico se come tradicionalmente el 25 de mayo?', options: ['El locro', 'La pizza', 'La milanesa', 'Los ravioles'] },
  { id: 'ar-obelisco', category: 'argentina', difficulty: 1, prompt: '¿En qué ciudad está el Obelisco más famoso del país?', options: ['Ciudad de Buenos Aires', 'Rosario', 'Córdoba', 'Mendoza'] },
  { id: 'ar-obelisco-anio', category: 'argentina', difficulty: 3, prompt: '¿En qué año se construyó el Obelisco de Buenos Aires?', options: ['1936', '1910', '1953', '1880'] },
  { id: 'ar-perito-moreno', category: 'argentina', difficulty: 2, prompt: '¿Cuál es el glaciar más famoso de la provincia de Santa Cruz?', options: ['El Perito Moreno', 'El Martial', 'El Tronador', 'El Lanín'] },
  { id: 'ar-moneda', category: 'argentina', difficulty: 1, prompt: '¿Cuál es la moneda de la Argentina?', options: ['El peso', 'El real', 'El dólar', 'El euro'] },
  { id: 'ar-tango', category: 'argentina', difficulty: 1, prompt: '¿Qué música y baile nació en el Río de la Plata a fines del siglo XIX?', options: ['El tango', 'La cumbia', 'El reggaetón', 'La salsa'] },
  { id: 'ar-bandoneon', category: 'argentina', difficulty: 2, prompt: '¿Qué instrumento es típico del tango?', options: ['El bandoneón', 'El charango', 'La gaita', 'El arpa'] },
  { id: 'ar-capital-pais', category: 'argentina', difficulty: 1, prompt: '¿Cuál es la capital de la Argentina?', options: ['Ciudad de Buenos Aires', 'Córdoba', 'Rosario', 'La Plata'] },

  // Fútbol
  { id: 'fut-mundiales', category: 'football', difficulty: 1, prompt: '¿Cuántas Copas del Mundo ganó la Selección Argentina?', options: ['3', '2', '4', '1'] },
  { id: 'fut-qatar', category: 'football', difficulty: 1, prompt: '¿En qué país se jugó el Mundial que Argentina ganó en 2022?', options: ['Catar', 'Rusia', 'Brasil', 'Estados Unidos'] },
  { id: 'fut-primer-mundial', category: 'football', difficulty: 2, prompt: '¿En qué año ganó Argentina su primer Mundial?', options: ['1978', '1986', '1930', '1966'] },
  { id: 'fut-capitan-86', category: 'football', difficulty: 2, prompt: '¿Quién era el capitán de Argentina en el Mundial de 1986?', options: ['Diego Maradona', 'Daniel Passarella', 'Jorge Valdano', 'Jorge Burruchaga'] },
  { id: 'fut-numero-diego', category: 'football', difficulty: 1, prompt: '¿Qué número de camiseta usaba Maradona en la Selección?', options: ['10', '9', '7', '11'] },
  { id: 'fut-debut-messi', category: 'football', difficulty: 3, prompt: '¿En qué club debutó Lionel Messi como profesional?', options: ['Barcelona', "Newell's Old Boys", 'Rosario Central', 'River Plate'] },
  { id: 'fut-bombonera', category: 'football', difficulty: 1, prompt: '¿Cómo se apoda al estadio de Boca Juniors?', options: ['La Bombonera', 'El Monumental', 'El Cilindro', 'El Gasómetro'] },
  { id: 'fut-academia', category: 'football', difficulty: 2, prompt: '¿Qué club es conocido como "La Academia"?', options: ['Racing Club', 'Independiente', 'Estudiantes', 'San Lorenzo'] },
  { id: 'fut-libertadores', category: 'football', difficulty: 3, prompt: '¿Qué club ganó más veces la Copa Libertadores?', options: ['Independiente', 'Boca Juniors', 'River Plate', 'Estudiantes'] },
  { id: 'fut-jugadores', category: 'football', difficulty: 1, prompt: '¿Cuántos jugadores tiene cada equipo de fútbol en la cancha?', options: ['11', '10', '9', '12'] },
  { id: 'fut-dibu', category: 'football', difficulty: 2, prompt: '¿Quién fue el arquero titular de Argentina en el Mundial 2022?', options: ['Emiliano "Dibu" Martínez', 'Franco Armani', 'Sergio Romero', 'Gerónimo Rulli'] },
  { id: 'fut-gotze', category: 'football', difficulty: 3, prompt: '¿Quién hizo el gol de Alemania en la final del Mundial 2014 contra Argentina?', options: ['Mario Götze', 'Thomas Müller', 'Miroslav Klose', 'Toni Kroos'] },
  { id: 'fut-copa-america', category: 'football', difficulty: 3, prompt: '¿Cuántas Copas América había ganado Argentina después de la de 2024?', options: ['16', '15', '14', '12'] },
  { id: 'fut-monumental', category: 'football', difficulty: 1, prompt: '¿De qué club es el estadio Monumental?', options: ['River Plate', 'Boca Juniors', 'Racing Club', 'Vélez Sarsfield'] },

  // Geografía
  { id: 'geo-capital-cordoba', category: 'geography', difficulty: 1, prompt: '¿Cuál es la capital de la provincia de Córdoba?', options: ['Córdoba', 'Villa María', 'Río Cuarto', 'Villa Carlos Paz'] },
  { id: 'geo-aconcagua', category: 'geography', difficulty: 1, prompt: '¿Cuál es la montaña más alta de América?', options: ['El Aconcagua', 'El Ojos del Salado', 'El Chimborazo', 'El Huascarán'] },
  { id: 'geo-cataratas', category: 'geography', difficulty: 1, prompt: '¿En qué provincia están las Cataratas del Iguazú?', options: ['Misiones', 'Corrientes', 'Salta', 'Entre Ríos'] },
  { id: 'geo-austral', category: 'geography', difficulty: 2, prompt: '¿Cuál es la provincia más austral de la Argentina?', options: ['Tierra del Fuego', 'Santa Cruz', 'Chubut', 'Río Negro'] },
  { id: 'geo-rio-uruguay', category: 'geography', difficulty: 2, prompt: '¿Qué río separa a la Argentina del Uruguay?', options: ['El río Uruguay', 'El río Paraná', 'El río Pilcomayo', 'El río Bermejo'] },
  { id: 'geo-limites', category: 'geography', difficulty: 2, prompt: '¿Con cuántos países limita la Argentina?', options: ['5', '4', '6', '3'] },
  { id: 'geo-oceano', category: 'geography', difficulty: 1, prompt: '¿Qué océano baña las costas argentinas?', options: ['El Atlántico', 'El Pacífico', 'El Índico', 'El Ártico'] },
  { id: 'geo-capital-mendoza', category: 'geography', difficulty: 1, prompt: '¿Cuál es la capital de la provincia de Mendoza?', options: ['Mendoza', 'San Rafael', 'Godoy Cruz', 'Malargüe'] },
  { id: 'geo-humahuaca', category: 'geography', difficulty: 2, prompt: '¿En qué provincia está la Quebrada de Humahuaca?', options: ['Jujuy', 'Salta', 'Tucumán', 'Catamarca'] },
  { id: 'geo-provincia-grande', category: 'geography', difficulty: 3, prompt: '¿Cuál es la provincia más grande del territorio continental argentino?', options: ['Buenos Aires', 'Santa Cruz', 'Chubut', 'Río Negro'] },
  { id: 'geo-pais-grande', category: 'geography', difficulty: 1, prompt: '¿Cuál es el país más grande de América del Sur?', options: ['Brasil', 'Argentina', 'Perú', 'Colombia'] },
  { id: 'geo-capital-chile', category: 'geography', difficulty: 1, prompt: '¿Cuál es la capital de Chile?', options: ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta'] },
  { id: 'geo-continente', category: 'geography', difficulty: 1, prompt: '¿Cuál es el continente más grande?', options: ['Asia', 'África', 'América', 'Europa'] },
  { id: 'geo-australia', category: 'geography', difficulty: 3, prompt: '¿Cuál es la capital de Australia?', options: ['Canberra', 'Sídney', 'Melbourne', 'Perth'] },
  { id: 'geo-egipto', category: 'geography', difficulty: 2, prompt: '¿En qué continente está Egipto?', options: ['África', 'Asia', 'Europa', 'Oceanía'] },
  { id: 'geo-rosario', category: 'geography', difficulty: 2, prompt: '¿Cuál es la ciudad con más habitantes de la provincia de Santa Fe?', options: ['Rosario', 'Santa Fe', 'Rafaela', 'Venado Tuerto'] },
  { id: 'geo-parana', category: 'geography', difficulty: 2, prompt: '¿De qué provincia es capital la ciudad de Paraná?', options: ['Entre Ríos', 'Corrientes', 'Santa Fe', 'Misiones'] },
  { id: 'geo-neuquen', category: 'geography', difficulty: 2, prompt: '¿Cuál es la capital de la provincia de Neuquén?', options: ['Neuquén', 'San Martín de los Andes', 'Zapala', 'Cutral Có'] },
  { id: 'geo-continente-ar', category: 'geography', difficulty: 1, prompt: '¿En qué continente está la Argentina?', options: ['América', 'Europa', 'África', 'Oceanía'] },

  // Historia
  { id: 'his-independencia', category: 'history', difficulty: 1, prompt: '¿En qué año se declaró la independencia argentina?', options: ['1816', '1810', '1853', '1806'] },
  { id: 'his-tucuman', category: 'history', difficulty: 2, prompt: '¿En qué ciudad se declaró la independencia argentina?', options: ['San Miguel de Tucumán', 'Buenos Aires', 'Córdoba', 'Salta'] },
  { id: 'his-cruce-andes', category: 'history', difficulty: 1, prompt: '¿Quién cruzó los Andes para liberar Chile y Perú?', options: ['José de San Martín', 'Manuel Belgrano', 'Martín Miguel de Güemes', 'Simón Bolívar'] },
  { id: 'his-constitucion', category: 'history', difficulty: 3, prompt: '¿En qué año se sancionó la Constitución Nacional argentina?', options: ['1853', '1816', '1810', '1880'] },
  { id: 'his-sarmiento', category: 'history', difficulty: 2, prompt: '¿Qué presidente argentino es conocido como "el padre del aula"?', options: ['Domingo F. Sarmiento', 'Bartolomé Mitre', 'Nicolás Avellaneda', 'Julio A. Roca'] },
  { id: 'his-malvinas', category: 'history', difficulty: 2, prompt: '¿En qué año fue la Guerra de Malvinas?', options: ['1982', '1978', '1976', '1986'] },
  { id: 'his-democracia', category: 'history', difficulty: 2, prompt: '¿En qué año volvió la democracia a la Argentina tras la última dictadura?', options: ['1983', '1982', '1989', '1976'] },
  { id: 'his-colon', category: 'history', difficulty: 1, prompt: '¿Quién llegó a América en 1492 con tres carabelas?', options: ['Cristóbal Colón', 'Américo Vespucio', 'Hernán Cortés', 'Fernando de Magallanes'] },
  { id: 'his-virreinato', category: 'history', difficulty: 3, prompt: '¿Qué virreinato tenía su capital en Buenos Aires?', options: ['El del Río de la Plata', 'El del Perú', 'El de Nueva Granada', 'El de Nueva España'] },
  { id: 'his-primera-presidenta', category: 'history', difficulty: 3, prompt: '¿Quién fue la primera mujer presidenta de la Argentina?', options: ['María Estela Martínez de Perón', 'Cristina Fernández de Kirchner', 'Eva Perón', 'Alicia Moreau de Justo'] },
  { id: 'his-voto-femenino', category: 'history', difficulty: 3, prompt: '¿Qué derecho consiguieron las mujeres argentinas con la ley de 1947?', options: ['Votar', 'Divorciarse', 'Jubilarse', 'Trabajar'] },
  { id: 'his-machu-picchu', category: 'history', difficulty: 2, prompt: '¿Qué civilización construyó Machu Picchu?', options: ['Los incas', 'Los mayas', 'Los aztecas', 'Los olmecas'] },
  { id: 'his-luna', category: 'history', difficulty: 2, prompt: '¿Quién fue la primera persona en pisar la Luna?', options: ['Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'] },
  { id: 'his-martin-fierro', category: 'history', difficulty: 2, prompt: '¿Quién escribió el "Martín Fierro"?', options: ['José Hernández', 'Domingo F. Sarmiento', 'Leopoldo Lugones', 'Esteban Echeverría'] },

  // Cultura general y deportes
  { id: 'gen-bisiesto', category: 'general', difficulty: 1, prompt: '¿Cuántos días tiene un año bisiesto?', options: ['366', '365', '364', '367'] },
  { id: 'gen-guitarra', category: 'general', difficulty: 1, prompt: '¿Cuántas cuerdas tiene una guitarra criolla?', options: ['6', '4', '8', '12'] },
  { id: 'gen-arcoiris', category: 'general', difficulty: 1, prompt: 'Según la tradición, ¿cuántos colores tiene el arcoíris?', options: ['7', '6', '5', '8'] },
  { id: 'gen-quijote', category: 'general', difficulty: 1, prompt: '¿En qué idioma se escribió originalmente "Don Quijote de la Mancha"?', options: ['Español', 'Latín', 'Italiano', 'Portugués'] },
  { id: 'gen-minutos-dia', category: 'general', difficulty: 2, prompt: '¿Cuántos minutos tiene un día?', options: ['1.440', '1.240', '1.400', '1.640'] },
  { id: 'gen-hexagono', category: 'general', difficulty: 1, prompt: '¿Cuántos lados tiene un hexágono?', options: ['6', '5', '7', '8'] },
  { id: 'gen-7x8', category: 'general', difficulty: 1, prompt: '¿Cuánto es 7 × 8?', options: ['56', '54', '48', '64'] },
  { id: 'gen-borges', category: 'general', difficulty: 3, prompt: '¿Qué escritor argentino escribió "El Aleph"?', options: ['Jorge Luis Borges', 'Julio Cortázar', 'Ernesto Sabato', 'Adolfo Bioy Casares'] },
  { id: 'gen-ginobili', category: 'general', difficulty: 2, prompt: '¿En qué deporte se destacó Manu Ginóbili?', options: ['Básquet', 'Tenis', 'Fútbol', 'Rugby'] },
  { id: 'gen-leonas', category: 'general', difficulty: 2, prompt: '¿Qué deporte juegan Las Leonas?', options: ['Hockey sobre césped', 'Vóley', 'Handball', 'Rugby'] },
  { id: 'gen-pumas', category: 'general', difficulty: 2, prompt: '¿Cómo se llama el seleccionado argentino de rugby?', options: ['Los Pumas', 'Los Leones', 'Los Cóndores', 'Los Gladiadores'] },
  { id: 'gen-delpo', category: 'general', difficulty: 3, prompt: '¿Qué tenista argentino ganó el US Open en 2009?', options: ['Juan Martín del Potro', 'Guillermo Vilas', 'David Nalbandian', 'Gastón Gaudio'] },

  // Ciencia y naturaleza
  { id: 'cie-jupiter', category: 'science', difficulty: 2, prompt: '¿Cuál es el planeta más grande del sistema solar?', options: ['Júpiter', 'Saturno', 'Neptuno', 'La Tierra'] },
  { id: 'cie-marte', category: 'science', difficulty: 1, prompt: '¿Qué planeta es conocido como "el planeta rojo"?', options: ['Marte', 'Venus', 'Júpiter', 'Mercurio'] },
  { id: 'cie-fotosintesis', category: 'science', difficulty: 2, prompt: '¿Qué gas toman las plantas del aire para hacer la fotosíntesis?', options: ['Dióxido de carbono', 'Oxígeno', 'Nitrógeno', 'Helio'] },
  { id: 'cie-oro', category: 'science', difficulty: 2, prompt: '¿Cuál es el símbolo químico del oro?', options: ['Au', 'Ag', 'Or', 'Go'] },
  { id: 'cie-sodio', category: 'science', difficulty: 3, prompt: '¿Cuál es el símbolo químico del sodio?', options: ['Na', 'So', 'Sd', 'S'] },
  { id: 'cie-hervor', category: 'science', difficulty: 1, prompt: '¿A qué temperatura hierve el agua a nivel del mar?', options: ['100 °C', '90 °C', '80 °C', '120 °C'] },
  { id: 'cie-guepardo', category: 'science', difficulty: 2, prompt: '¿Cuál es el animal terrestre más rápido?', options: ['El guepardo', 'El león', 'El caballo', 'El galgo'] },
  { id: 'cie-arania', category: 'science', difficulty: 1, prompt: '¿Cuántas patas tiene una araña?', options: ['8', '6', '10', '12'] },
  { id: 'cie-ballena-azul', category: 'science', difficulty: 2, prompt: '¿Cuál es el animal más grande del mundo?', options: ['La ballena azul', 'El elefante africano', 'La jirafa', 'El tiburón ballena'] },
  { id: 'cie-piel', category: 'science', difficulty: 3, prompt: '¿Cuál es el órgano más grande del cuerpo humano?', options: ['La piel', 'El hígado', 'El corazón', 'El cerebro'] },
  { id: 'cie-pulpo', category: 'science', difficulty: 3, prompt: '¿Cuántos corazones tiene un pulpo?', options: ['3', '1', '2', '4'] },
  { id: 'cie-huesos', category: 'science', difficulty: 3, prompt: '¿Cuántos huesos tiene el cuerpo de una persona adulta?', options: ['206', '208', '196', '212'] },
  { id: 'cie-einstein', category: 'science', difficulty: 1, prompt: '¿Qué científico propuso la teoría de la relatividad?', options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Nikola Tesla'] },
  { id: 'cie-houssay', category: 'science', difficulty: 3, prompt: '¿Qué científico argentino ganó el Premio Nobel de Medicina en 1947?', options: ['Bernardo Houssay', 'Luis Federico Leloir', 'César Milstein', 'René Favaloro'] },
  { id: 'cie-favaloro', category: 'science', difficulty: 2, prompt: '¿Qué médico argentino desarrolló la cirugía de bypass coronario?', options: ['René Favaloro', 'Bernardo Houssay', 'Luis Agote', 'César Milstein'] },
  { id: 'cie-luna', category: 'science', difficulty: 1, prompt: '¿Cuál es el satélite natural de la Tierra?', options: ['La Luna', 'El Sol', 'Marte', 'Venus'] },
  { id: 'cie-rey-selva', category: 'science', difficulty: 1, prompt: '¿Qué animal es conocido como "el rey de la selva"?', options: ['El león', 'El tigre', 'El elefante', 'El gorila'] },

  // Entretenimiento
  { id: 'ent-mafalda', category: 'entertainment', difficulty: 1, prompt: '¿Qué personaje creó Quino?', options: ['Mafalda', 'Patoruzú', 'Isidoro Cañones', 'Clemente'] },
  { id: 'ent-donald', category: 'entertainment', difficulty: 1, prompt: '¿Cómo se llama el pato de Disney que usa traje de marinero?', options: ['Donald', 'Lucas', 'Pluto', 'Goofy'] },
  { id: 'ent-woody', category: 'entertainment', difficulty: 1, prompt: '¿En qué película aparece el vaquero Woody?', options: ['Toy Story', 'Shrek', 'Buscando a Nemo', 'Cars'] },
  { id: 'ent-gaturro', category: 'entertainment', difficulty: 2, prompt: '¿Qué historieta argentina tiene como protagonista a un gato?', options: ['Gaturro', 'Mafalda', 'Patoruzú', 'Clemente'] },
  { id: 'ent-ariel', category: 'entertainment', difficulty: 1, prompt: '¿Qué princesa de Disney es una sirena?', options: ['Ariel', 'Bella', 'Jazmín', 'Aurora'] },
  { id: 'ent-signos', category: 'entertainment', difficulty: 3, prompt: '¿Qué banda argentina grabó el disco "Signos"?', options: ['Soda Stereo', 'Los Redondos', 'Virus', 'Los Fabulosos Cadillacs'] },
  { id: 'ent-marvel', category: 'entertainment', difficulty: 1, prompt: '¿Cuál de estos superhéroes es de Marvel?', options: ['Spider-Man', 'Batman', 'Superman', 'Flash'] },
  { id: 'ent-eternauta', category: 'entertainment', difficulty: 3, prompt: '¿Cómo se llama el protagonista de "El Eternauta"?', options: ['Juan Salvo', 'Martín Fierro', 'Isidoro Cañones', 'Juan Moreira'] },
  { id: 'ent-piazzolla', category: 'entertainment', difficulty: 2, prompt: '¿Qué instrumento tocaba Astor Piazzolla?', options: ['El bandoneón', 'El piano', 'El violín', 'La guitarra'] },
  { id: 'ent-shrek', category: 'entertainment', difficulty: 1, prompt: '¿De qué color es Shrek?', options: ['Verde', 'Azul', 'Gris', 'Amarillo'] },
];
